// <auto-generated />
using Infraestructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(EcommerceDbContext))]
    [Migration("20250207212844_Initial2")]
    partial class Initial2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Domain.Entities.Minorista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Dni")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameAccount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeUser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Minoristas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Santafe 1234",
                            Dni = 12323456,
                            Email = "facu@hotmail.com",
                            FirstName = "Facundo",
                            LastName = "Solari",
                            NameAccount = "facu",
                            Password = "facu123",
                            PhoneNumber = "+543413500300",
                            TypeUser = "Minorista"
                        },
                        new
                        {
                            Id = 2,
                            Address = "San Lorenzo 3624",
                            Dni = 34732713,
                            Email = "cris@hotmail.com",
                            FirstName = "Cristian",
                            LastName = "Ninotti",
                            NameAccount = "cris",
                            Password = "cris123",
                            PhoneNumber = "+543415155611",
                            TypeUser = "Minorista"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
